apiVersion: v1
kind: Service
metadata:
  name: banking-integration-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: banking-integration
